### ISSUE TITLE
Error decoding some rev3 files

### ISSUE THREAD

**Issue by bnnm** [daddesio/utkencode#1]
Hi, I found some rev3 files that don't decode properly (SSX3 PS2). They seem to read past a frame, making the PCM offset/count values fail.

Files are EA .bnk format (similar to SCxl without blocks). Actual MicroTalk data in .bnk starts at 0x50. To facilitate testing I've made a couple of fake .utk with data from the .bnk  (since this fix is mainly for vgmstream, it's not important that utkencode supports .bnk). When `utkdecode.c` decodes using `utk_rev3_decode_frame`, one .utk decodes properly and other doesn't.

Samples: [utk-rev3-bug.zip](https://github.com/daddesio/utkencode/files/2354823/utk-rev3-bug.zip)

In Bear1.utk, frame fails at 0x20 (data start) + 0x3be. It should read up to 0x20+0x3da (where PCM offset/count start), but instead reads up to 0x20+0x3fe. Bitstream seems fairly complex, so I don't know what could be failing.

Thanks!

EDIT: forgot to mention, the files play fine in sx.exe 3.0

**Comment by daddesio** [comment]
It's another container idiosyncrasy. It turns out for looped samples (with a 0x86 field present in the PT header), the intro and the loop are two separate MicroTalk streams, so you need to reinitialize the decoder (e.g. memset it to zero) before decoding the second stream. (In particular, make sure that utk->header_parsed = false.) The first stream contains `pt_get_int(0x86)` samples, and the second stream contains `(pt_get_int(0x87) + 1) - pt_get_int(0x86)` samples. I'm not sure if there's a third stream for the outro.

The relevant code in sx v3.01.01 is 00418113 (you can see it call utk_init/utk_decode_n_samples for the intro and again for the loop, where 0042730A = utk_init, 004273C7 = utk_decode_n_samples).

**Comment by bnnm** [comment]
You are completely right, thanks a lot. After some tweaks I got them working. I should've known better, since EA does this with other codecs too.

A few still fail though, were loop is smaller than 1 frame/432 samples (but bigger than 0). May be a problem in utkencode this time? Samples: [utk-rev3-bug2.zip](https://github.com/daddesio/utkencode/files/2363496/utk-rev3-bug2.zip)

For instance take GoGo1.bnk, data starts at 0x50. After reading first frame (right after a decoder reset), I see the decoder ends in 0x50+5D and reads pcm_count = 0.
However looking at the data, I believe it should end at 0x50+23 and reads 0xc1 samples, so next frame (where I'd reset the decoder for looping) would be 0x50+1a9.
Same file removing the first frame manually plays fine.


Hope you don't mind taking another look, thanks!

**Comment by daddesio** [comment]
> However looking at the data, I believe it should end at 0x50+23 and reads 0xc1 samples, so next frame (where I'd reset the decoder for looping) would be **0x50+1a9**.

Okay, I verified my decoder behaves exactly the same as sx. In GoGo1.bnk, sx also reads pcm_offset = 0x0000 at 0x50+0x5d, pcm_count = 0x0000 at 0x50+0x5f, and doesn't even look at the PCM data ("FF FF 00 01 ...").

It turns out that the 0x1a9 offset for the second MT stream (the "loop") is coming from the 0x1a field in the PT header. All the PCM-looking data you see ("FF FF 00 01 FF FE 00 05 ... F4 FF FB FF") is garbage data.

By creating multi-channel MicroTalk samples with sx (`sx.exe -pcbank -mt_blk -notruncate -loops123 -loope456 infile.wav -=outfile.bnk` where infile.wav has 1 to 6 channels) I figured out the fields for all channels 1-6:

| Field  | Meaning                         |
| ------ | ------------------------------- |
| 0x1a   | Byte offset to loop (channel 1) |
| 0x26   | Byte offset to loop (channel 2) |
| 0x27   | Byte offset to loop (channel 3) |
| 0x28   | Byte offset to loop (channel 4) |
| 0x29   | Byte offset to loop (channel 5) |
| 0x2a   | Byte offset to loop (channel 6) |

I tried adding `-notruncate` to the sx command in various places but it always seems to truncate the sound after the loop end, so it seems there is no "Byte offset to outro" field and outros in Microtalk are not supported.

**Comment by bnnm** [comment]
Thanks a lot, I was able to fix looping with that info, case closed.

I tested sx.exe a bit and seems other "VBR" codecs (EA-XA with PCM blocks) also have loop offsets, while the rest don't as are easy to derive I guess.
